config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  
  get '/register', to: 'users#new'
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :categories, only: [:new, :create, :show, :edit, :update, :index, :destroy]
  resources :users, only: [:index, :show, :create, :edit, :update]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post
  validates :body, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
  
  def create
    @post = Post.find_by(title: params[:post_id])
    @comment = Comment.new(params.require(:comment).permit(:body))
    @comment.creator = current_user
    
    if @comment.save
      @comment.post = @post # adding this here to cover when the comment cannot be saved due to being empty.  Otherwise, shows a blank comment at the bottom of the list of comments.
      @comment.save
      flash[:notice] = "Comment successfully added!"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.new(vote: params[:vote], voteable: @comment, creator: current_user)

    if @vote.save
      respond_to do |format|
        format.html {redirect_to :back, notice: "Your vote counted for that comment."}
        format.js
      end
    else
      flash[:errors] = "You already voted for that comment."
      redirect_to :back
    end
  end

end

app/views/comments/_comment.html.erb
<% show_post ||= false %>

<div class='row'>
  <div id="comment_<%= comment.id %>_vote">
    <%= render 'comments/vote_comment', voteable_obj: comment %>
  </div>
  <div class='well span6'>
    <em>"<%= comment.body %>"</em>
    <% if show_post %>
    on <%= link_to comment.post.title, post_path(comment.post) %>
    <% end %>
    <br/>
    <span class='quiet'>says</span> <%= link_to comment.creator.username, user_path(comment.creator) %>
    <small><%= tell_time_posted(comment.created_at) %></small>
  </div>
</div>

app/views/comments/_form.html.erb
<!-- Comment Form -->
<%= render 'shared/errors', object: @comment %>

<%= form_for [@post, @comment] do |f| %>
  <%= f.label :body, "Leave a comment" %>
  <%= f.text_area :body, rows: 3, class: "span4" %>
  <br/>
  <%= f.submit "Submit Comment", class: "btn btn-primary"%>
<% end %>

app/views/comments/_vote_comment.html.erb
<% user_can_vote = voteable_obj.votes.select{|vote| vote.creator == current_user}.empty? && logged_in? %>

<div class= 'well span1' align="center">
  <% if user_can_vote %>
    <%= link_to vote_post_comment_path(voteable_obj.post, voteable_obj, vote: true), method: "post", remote: true do %>
      <i class='icon-plus'></i>
    <% end %>
    <br/>
  <% end %>
  <%= pluralize(voteable_obj.total_votes, "Vote") %>
  <% if user_can_vote %>
    <br/>
    <%= link_to vote_post_comment_path(voteable_obj.post, voteable_obj, vote: false), method: "post", remote: true do %>
      <i class='icon-minus'></i>
    <% end %>
  <% end %>
</div>

app/views/comments/vote.js.erb
$("#comment_<%= @comment.id %>_vote").html("<%= escape_javascript(render 'comments/vote_comment', voteable_obj: @comment) %>")