config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  
  get '/register', to: 'users#new'
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :categories, only: [:new, :create, :show, :edit, :update, :index, :destroy]
  resources :users, only: [:index, :show, :create, :edit, :update]

end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  

  validates :title, presence: true, length: {minimum: 5}, uniqueness: true
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true

  sluggable_column :title

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :set_new_comment, only: [:show]
  before_action :require_user, except: [:show, :index]
  before_action :require_creator_or_admin_to_edit, only: [:edit, :update]

  def index
    @posts = Post.all.sort do |x, y|
      unless (y.total_votes <=> x.total_votes) == 0
        y.total_votes <=> x.total_votes
      else
        y.created_at <=> x.created_at
      end
    end
  end

  def show; end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to post_path(@post)
    else
      render 'new'
    end

  end

  def edit; end

  def update
    # before_action set_post
    if @post.update(post_params)
      flash[:notice] = "\"#{@post.title}\" was updated."
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def vote
    @vote = Vote.new(vote: params[:vote], creator: current_user, voteable: @post)

    if @vote.save
      respond_to do |format|
        flash[:notice] = "Your vote was counted."
        format.html { redirect_to :back}
        format.js
      end
    else
      flash[:errors] = "You have already voted for that."
      redirect_to :back
    end
  end

  private

  def post_params
    params.require(:post).permit!
  end

  def set_post
    @post = Post.find_by(slug: params[:id])
  end

  def set_new_comment
    @comment = Comment.new
    @comment.creator = User.first
  end

  def require_creator_to_edit
    unless current_user_is_creator?(@post)
      you_cant_do_that
    end
  end

  def require_creator_or_admin_to_edit
    unless current_user_is_creator?(@post) || current_user_is_admin?
      you_cant_do_that
    end
  end

  def you_cant_do_that
    flash[:errors] = "You can't do that."
    redirect_to post_path(@post)
  end

end

app/views/posts/_form.html.erb
<!-- Post form template -->
<%= render 'shared/errors', object: @post %>

<div class='well'>
<%= form_for @post do |f| %>
  <div class='control-group'>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class='control-group'>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class='control-group'>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 5 %>
    <br/>
  </div>

  <div class='control-group'>
    <%= f.label "Categories" %>
    <%= f.collection_check_boxes :category_ids, Category.all.sort_by{|cat| cat[:name].capitalize}, :id, :name do |cb| %>
      <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </div>

  <div class='control-group'>
    <%= f.submit submit_text, class: "btn btn-primary" %>
  </div>
  <div class='control-group'>
    <%= link_to "Cancel", post_path(@post), type: "button", class: "btn btn-inverse" %>
  </div>
<% end %>
</div>

app/views/posts/_post_preview.html.erb
<div class = 'row'>
  <div id="post_<%= post.slug%>_votes">
  <%= render 'posts/vote_post', voteable_obj: post %>
  </div>
  <div class= 'well span7'>
    <%= render post.categories %>
    <h4><%= link_to post.title, post_path(post)%></h4>
    <p><%= post.description %></p>
    <p>
      <span class='quiet'>posted by </span><%= link_to post.creator.username, user_path(post.creator) %>
      <small>Posted <%= tell_time_posted(post.created_at)%></small>
    </p>
    <hr/>
    <%= link_to post_path(post) do %>
      <%= pluralize(post.comments.size, "comment") %>
    <% end %>
    <% unless post.comments.empty? %>
      <div class='inline pull-right'>
        <span class='quiet'>last comment made</span>
        <%= tell_time_posted(post.comments.last.created_at) %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_vote_post.html.erb
<% user_can_vote = voteable_obj.votes.select{|vote| vote.creator == current_user}.empty? && logged_in? %>

<div class= 'well span1' align="center">
  <% if user_can_vote %>
    <%= link_to vote_post_path(voteable_obj, vote: true), method: "post", remote: true do %>
      <i class='icon-plus'></i>
    <% end %>
    <br/>
  <% end %>
  <%= pluralize(voteable_obj.total_votes, "Vote") %>
  <% if user_can_vote %>
    <br/>
    <%= link_to vote_post_path(voteable_obj, vote: false), method: "post", remote: true do %>
      <i class='icon-minus'></i>
    <% end %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Post' %>

<%= render 'form', submit_text: "Update Post" %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<% @posts.each do |post| %>
  <%= render 'post_preview', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: "Create New Post" %>

<%= render 'form', submit_text: "Submit New Post" %>

app/views/posts/show.html.erb
<% post_title = link_to(@post.title, fix_url(@post.url)) %>

<p>
  <%= render @post.categories %>
</p>
<hr/>

<% if logged_in? && (current_user_is_creator?(@post) || current_user_is_admin?) %>
  <p class="pull-right">
    <%= link_to 'Edit Post', edit_post_path(@post), class: "btn btn-inverse" %>
  </p>
<% end %>

<%= render 'shared/content_title', title: post_title %>


<div class='row'>
  <div class='span'>
    <p><%= @post.description %></p>
  </div>
</div>
<hr/>

<% if @post.comments.size > 0 %>
  <h6><%= @post.comments.size %> Comments</h6>
<% end %>

<% if logged_in? %>
  <%= render 'comments/form' %>
<% end %>

<% @post.comments.sort_by{|com| com[:created_at]}.reverse.each do |comment| %>
  <%= render "comments/comment", comment: comment %>
<% end %>

app/views/posts/vote.js.erb
$("#post_<%= @post.slug %>_votes").html("<%= escape_javascript(render 'posts/vote_post', voteable_obj: @post) %>")