config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  
  get '/register', to: 'users#new'
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :categories, only: [:new, :create, :show, :edit, :update, :index, :destroy]
  resources :users, only: [:index, :show, :create, :edit, :update]

end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable
  has_many :post_categories
  has_many :posts, through: :post_categories
  validates :name, presence: true, length: {maximum: 20}, uniqueness: true

  sluggable_column :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :set_category, only: [:show, :edit, :update]

  def index
    @categories = Category.all.sort{|x,y| x.name.downcase <=> y.name.downcase}
  end

  def show
    @category = Category.find_by(slug: params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "#{@category.name} category created successfully!"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category successfully updated!"
      redirect_to categories_path
    else
      render :edit
    end
  end

  private
  def set_category
    @category = Category.find_by(slug: params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end


end

app/views/categories/_category.html.erb
<span class='badge'>
  <%= link_to category.name, category_path(category) %>
</span>

app/views/categories/_form.html.erb
<!-- Category form -->

<%= render 'shared/errors', object: @category %>

<%= form_for @category do |f| %>
  <%= f.label :name, "Category" %>
  <%= f.text_field :name %>
  <br/>
  <%= f.submit submit_text, class: "btn btn-primary" %>
<% end %>

app/views/categories/edit.html.erb
<%= render "shared/content_title", title: "Edit Category" %>

<%= render "form", submit_text: "Update"  %>

app/views/categories/index.html.erb
<%= render 'shared/content_title', title: "Categories" %>

<div class="row">
  <div class="span">
    <%= link_to "Add New Category", new_category_path, class: "btn btn-success" %>
  </div>
  <div class="span">
    <%= link_to "Back to Root", root_path, class: "btn" %>
  </div>
</div>
<hr/>
<h4>Edit Categories</h4>
<br/>
<% @categories.each do |category| %>
  <p>
    <%= link_to(edit_category_path(category), class: 'btn btn-warning') do %>
      <i class="icon-edit icon-white"></i> <%= category.name %>
    <% end %>
  </p>

  <br/>
<% end %>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: "Add New Category" %>

<% if @category.errors.any? %>
  <div class='row'>
    <div class='alert alert-error'>
      <h4>Invalid Category</h4>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>
<div class='well'>
  <%= form_for @category do |f| %>
    <%= f.label :name, "Category" %>
    <%= f.text_field :name %>
    <br/>
    <%= f.submit "Add Category", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% header = link_to('All Posts', posts_path) + " &raquo; #{@category.name}".html_safe %>

<%= render 'shared/content_title', title: header %>

<% @category.posts.sort{|x, y| x.total_votes <=> y.total_votes}.reverse.each do |post| %>
<%= render 'posts/post_preview', post: post %>
<% end %>

<% if @category.posts.empty? %>
  
<% end %>